theme = "gruvbox"

[editor]
auto-save = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-p = "file_picker"
C-tab = "goto_last_accessed_file"
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"%" = "match_brackets"
A-f = ":format"

[keys.normal.space]
f = ":format"
space = ":w"

[keys.insert]
C-p = "file_picker"
C-space = "completion"
C-tab = "goto_last_accessed_file"
