theme = "gruvbox"

[editor]
auto-save = true
auto-format = true
auto-complete = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-p = "file_picker"

[keys.insert]
C-p = "file_picker"

