#!/bin/bash

# NOK='%{F#f38ba8}'
NOK='%{F#a6adc8}'
OK='%{F#f5e0dc}'

MIC_ON="echo $OK"
MIC_OFF="echo $NOK"

pactl get-source-mute 1 | awk '/Mute: sim/ { system("'"$MIC_OFF"'") } /Mute: não/ { system("'"$MIC_ON"'") }'
