#!/bin/bash

# NOK='%{F#f38ba8}'
NOK='%{F#fb4934}'
OK='%{F#b8bb26}'

MIC_ON="echo $OK"
MIC_OFF="echo $NOK"

pactl get-source-mute @DEFAULT_SOURCE@ | awk '/Mute: yes/ { system("'"$MIC_OFF"'") } /Mute: no/ { system("'"$MIC_ON"'") }'
