#!/bin/bash

# NOK='%{F#f38ba8}'
NOK='%{F#fb4934}'
OK='%{F#b8bb26}'

MIC_ON="echo $OK"
MIC_OFF="echo $NOK"

pactl get-source-mute 1 | awk '/Mute: sim/ { system("'"$MIC_OFF"'") } /Mute: não/ { system("'"$MIC_ON"'") }'
