#!/bin/bash

volume_info=$(pactl get-sink-volume 0)

left_percentage=$(echo "$volume_info" | awk -F 'front-left:' 'NR==1 {print $2}' | awk -F '/' '{print $2}' | tr -d '%')
right_percentage=$(echo "$volume_info" | awk -F 'front-right:' 'NR==1 {print $2}' | awk -F '/' '{print $2}' | tr -d '%')

max_percentage=$((left_percentage > right_percentage ? left_percentage : right_percentage))

dunstify -a bottom-center -r 99998 -u normal -h int:value:$max_percentage " Audio             $max_percentage%" -t 1000
