#!/usr/bin/env python

import sys
import pyperclip


unicodes = sys.argv[1:]

for unicode in range(len(unicodes)):
    code = unicodes[unicode].lower()
    pyperclip.copy(chr(int(code, 16)))
    input(f"{chr(int(code, 16))} - Press Enter to continue... ")
